import { useState } from 'react'

type FlowStep = 1 | 2 | 3 | 4
type Tab = 'setup' | 'research' | 'plan' | 'today'
type ResourceStatus = '待审核' | '已确认' | '暂缓' | '已放弃'
type Resource = { title: string; source: string; topic: string; summary: string; reason: string; minutes: number; status: ResourceStatus }

const stages = [
  ['第 1 周', '建立起点', '明确目标、能力盘点与安全待确认问题'], ['第 2 周', '理解 Agent 基础', '理解 Agent、模型、工具与任务之间的关系'], ['第 3 周', '完成最小练习', '用一个简单场景练习提示词与工具调用'], ['第 4 周', '分析边界', '明确目标、指标、基准与可回答问题'],
  ['第 5 周', '问题拆解', '把一个分析任务拆成可执行的步骤'], ['第 6 周', '取数与工具调用', '理解数据读取、工具选择与错误处理'], ['第 7 周', '形成回答', '练习从证据到结论的分析过程'], ['第 8 周', '真实场景准备', '梳理可用于练习的真实业务场景'], ['第 9 周', '场景复盘', '在获批范围内核对历史 campaign'], ['第 10 周', '形成交付计划', '输出搭建计划、风险和验收方式'],
]
const initialResources: Resource[] = [
  { title: 'Agent 基础概念', source: '官方资料 · 示例', topic: '理解 Agent', summary: '理解 Agent、模型、工具和任务之间的关系。', reason: '帮助建立共同语言，适合当前入门阶段。', minutes: 45, status: '待审核' },
  { title: '工具调用与错误处理', source: '官方资料 · 示例', topic: '工具调用', summary: '通过小例子理解工具选择、参数和失败处理。', reason: '对应你希望优先解决的实践问题。', minutes: 60, status: '待审核' },
  { title: 'Campaign 指标与基准', source: '手动资料 · 示例', topic: '分析边界', summary: '梳理指标、基准和可回答问题的边界。', reason: '为后续真实场景练习准备分析框架。', minutes: 50, status: '待审核' },
]
const dailyTasks = [
  ['理解 Agent 的基本组成', '阅读“Agent 基础概念” · 预计 30 分钟 · 完成条件：能说清 Agent、模型和工具的关系'],
  ['完成一次最小工具调用', '阅读“工具调用与错误处理” · 预计 35 分钟 · 完成条件：描述一次成功和一次失败调用'],
  ['记录三个待解决问题', '回顾前两天内容 · 预计 20 分钟 · 完成条件：写下 3 个具体问题'],
]

function App() {
  const [step, setStep] = useState<FlowStep>(1); const [tab, setTab] = useState<Tab>('setup'); const [goal, setGoal] = useState(''); const [submitted, setSubmitted] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [resources, setResources] = useState(initialResources); const [selectedResource, setSelectedResource] = useState<string | null>(null); const [researchState, setResearchState] = useState<'完成' | '研究中' | '失败'>('完成'); const [todayStarted, setTodayStarted] = useState(false); const [todayCompleted, setTodayCompleted] = useState(false); const [recordSaved, setRecordSaved] = useState(false); const [scheduleNote, setScheduleNote] = useState(''); const [day, setDay] = useState(1); const [resting, setResting] = useState(false); const [completedDays, setCompletedDays] = useState<number[]>([])
  const currentTask = dailyTasks[(day - 1) % dailyTasks.length]
  const advanceDay = () => { setCompletedDays(days => days.includes(day) ? days : [...days, day]); setDay(value => value + 1); setTodayStarted(false); setTodayCompleted(false); setRecordSaved(false); setResting(false); setScheduleNote('') }
  const go = (next: FlowStep, nextTab: Tab) => { setStep(next); setTab(nextTab) }
  const tabs: [Tab, string][] = [['setup', '建立起点'], ['research', '资料收集'], ['plan', '学习计划'], ['today', '今日启动']]
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">A</span><span>Agent Study Lab</span></div><span className="step-tag">个人学习工作台 · 模拟版本</span></header>
    <section className="hero compact"><div className="eyebrow">START YOUR LEARNING PLAN</div><h1>先明晰计划，<br /><em>再开始学习。</em></h1><p>把你的目标、基础和可投入时间告诉我。我会先收集合适的资料，再制作一份由你确认的学习计划。</p></section>
    {step < 4 && <><div className="start-intro"><span className="start-kicker">LET'S START</span></div><div className="flow-steps" aria-label="Let's start 学习计划流程">{[['1', '输入条件'], ['2', '收集资料'], ['3', '确认计划']].map(([number, label], index) => { const current = index + 1; return <button key={number} type="button" className={step === current ? 'flow-step current' : step > current ? 'flow-step done' : 'flow-step'} onClick={() => current <= step && go(current as FlowStep, tabs[index][0])}><span>{step > current ? '✓' : number}</span>{label}</button> })}</div></>}
    {step >= 4 && <section className={archiveOpen ? 'archive open' : 'archive'}><button type="button" className="archive-toggle" onClick={() => setArchiveOpen(value => !value)}><span><strong>点击这里查看学习计划</strong></span><span className="archive-chevron">⌄</span></button>{archiveOpen && <div className="archive-body"><div className="archive-steps"><button onClick={() => go(1, 'setup')}><span>✓</span>输入条件</button><button onClick={() => go(2, 'research')}><span>✓</span>收集资料</button><button onClick={() => go(3, 'plan')}><span>✓</span>确认计划</button></div><p>这三个步骤共同完成学习计划，不需要每天重新进行。你可以随时展开查看或回顾。</p></div>}</section>}
    {step < 4 && <nav className="tabs" aria-label="工作台页面">{tabs.slice(0, 3).map(([key, label]) => <button key={key} type="button" className={tab === key ? 'active' : ''} onClick={() => { if (key === 'setup' || (key === 'research' && submitted) || (key === 'plan' && step >= 3)) setTab(key) }}>{label}</button>)}</nav>}
    {tab === 'setup' && <section className="panel setup-panel"><div className="panel-number">STEP 01 / 输入学习条件</div><h2>先告诉我，你想从哪里开始</h2><p>这些信息会帮助我筛选资料，并把学习计划安排在你的真实时间里。</p><div className="form-grid"><label className="full">你的学习目标<textarea value={goal} onChange={event => setGoal(event.target.value)} placeholder="例如：我想理解 Analytics Agent 的工作方式，并做出一个安全可控的最小原型。" /></label><label>现有基础<select defaultValue="有一些相关经验"><option>刚开始了解</option><option>有一些相关经验</option><option>已经做过项目</option></select></label><label>每周可投入时间<select defaultValue="每周约 270 分钟"><option>每周约 120 分钟</option><option>每周约 270 分钟</option><option>每周约 420 分钟</option></select></label><label>资料偏好<select defaultValue="中文为主，保留英文原文"><option>中文为主，保留英文原文</option><option>英文原文优先</option><option>短文与视频优先</option></select></label><label>希望优先解决的问题<input placeholder="例如：工具调用、指标口径、安全边界" /></label></div><div className="form-actions"><span>提交后先进入资料收集，不会直接生成计划。</span><button className="primary-button" disabled={!goal.trim()} onClick={() => { setSubmitted(true); go(2, 'research') }}>保存条件，开始收集资料 <span>→</span></button></div></section>}
    {tab === 'research' && <section className="panel list-panel"><div className="panel-number">STEP 02 / 资料收集</div><h2>围绕你的目标，找到值得学习的资料</h2><p>这是一次模拟研究结果。打开条目查看主旨、理由和来源，再决定是否纳入计划。</p><div className="research-banner"><span className="spinner">✦</span><div><strong>{researchState === '研究中' ? '正在整理 3 个主题…' : researchState === '失败' ? '研究暂时失败' : '已根据你的学习条件整理 3 个主题'}</strong><small>Agent 基础 · 工具调用 · 分析边界</small></div><span className="status">{researchState}</span></div>{researchState === '失败' && <div className="error-box">模拟网络错误：之前的有效结果仍保留。<button className="text-button" onClick={() => setResearchState('研究中')}>重试研究</button></div>}<div className="stage-list">{resources.map(resource => <div className="stage-row resource-row" key={resource.title} onClick={() => setSelectedResource(selectedResource === resource.title ? null : resource.title)}><span className="resource-icon">↗</span><div><strong>{resource.title}</strong><small>{resource.source} · {resource.topic} · {resource.minutes} 分钟</small>{selectedResource === resource.title && <div className="resource-detail"><p>{resource.summary}</p><small>推荐理由：{resource.reason}</small><div className="resource-actions"><button onClick={event => { event.stopPropagation(); setResources(items => items.map(item => item.title === resource.title ? { ...item, status: '已确认' } : item)) }}>确认</button><button onClick={event => { event.stopPropagation(); setResources(items => items.map(item => item.title === resource.title ? { ...item, status: '暂缓' } : item)) }}>暂缓</button><button onClick={event => { event.stopPropagation(); setResources(items => items.map(item => item.title === resource.title ? { ...item, status: '已放弃' } : item)) }}>放弃</button></div></div>}</div><span className="status">{resource.status}</span></div>)}</div><div className="form-actions"><span>已确认 {resources.filter(resource => resource.status === '已确认').length} 条资料 · 只有确认项会进入计划。</span><button className="primary-button" onClick={() => go(3, 'plan')}>用这些资料制作计划 <span>→</span></button></div></section>}
    {tab === 'plan' && <section className="panel plan-panel"><div className="panel-number">STEP 03 / 确认学习计划</div><h2>这是为你制作的 10 周学习计划</h2><p>计划会先作为草稿展示。确认后，才会进入日常学习。</p><div className="plan-summary"><div><small>学习目标</small><strong>{goal || '理解 Analytics Agent 并完成一个最小实践'}</strong></div><div><small>时间预算</small><strong>每周 4.5 小时</strong></div><div><small>已纳入资料</small><strong>{resources.filter(resource => resource.status === '已确认').length || 3} 条</strong></div></div><div className="budget-note">模拟提示：第 5 周预计 300 分钟，超过每周 270 分钟预算。你可以确认计划后再调整。</div><div className="stage-list">{stages.map(stage => <div className="stage-row" key={stage[0]}><span className="week">{stage[0]}</span><div><strong>{stage[1]}</strong><small>{stage[2]} · 预计 2–3 小时</small></div><span className="status">草稿</span></div>)}</div><div className="form-actions"><button className="text-button" onClick={() => go(2, 'research')}>← 返回查看资料</button><button className="primary-button" onClick={() => go(4, 'today')}>确认计划，开始今日学习 <span>→</span></button></div></section>}
    {tab === 'today' && <section className="grid"><article className="panel primary"><div className="panel-number">本周学习计划 / WEEK 01</div><h2>Agent 基础</h2><div className="today-date">2026 年 10 月 2 日 · 星期五</div><p>本周目标：建立对 Agent 的整体理解。</p><div className="week-tasks"><div><span>{completedDays.includes(1) ? '✓' : '○'}</span>理解 Agent、模型和工具</div><div><span>{completedDays.includes(2) ? '✓' : '○'}</span>完成一个最小工具调用练习</div><div><span>{completedDays.includes(3) ? '✓' : '○'}</span>记录 3 个仍未解决的问题</div></div><div className="progress"><span className={completedDays.length ? 'progress-complete' : ''} /></div><div className="meta"><span>本周进度</span><strong>{completedDays.length} / 3 项</strong></div></article><article className="panel"><div className="panel-number">WEEK 01 / DAY 0{day}</div><h2>今天学什么</h2>{scheduleNote && <div className="schedule-note">{scheduleNote}</div>}{!todayStarted && <div className="review-card"><strong>{day === 1 ? '今天是学习的第一天，享受当下吧。' : `今天是学习的第 ${day} 天，继续保持自己的节奏。`}</strong><p>完成今天的学习后，再回来记录你的理解、疑问和练习结果。</p></div>} {todayStarted && <div className="review-card"><span className="review-label">学习回顾</span><strong>{day === 1 ? '这是你的第一天，目前还没有过去的学习记录。' : '回顾昨天的学习记录，再开始今天的内容。'}</strong><p>今天先专注于当前任务，完成后再记录新的发现。</p></div>}<div className="today-task"><span>0{day}</span><div><strong>{currentTask[0]}</strong><small>{currentTask[1]}</small></div></div><div className="schedule-actions"><button onClick={() => { if (resting) advanceDay(); else if (!todayCompleted) setScheduleNote('先完成今天的份额哦'); else if (!recordSaved) setScheduleNote('先保存今天的学习记录哦'); else advanceDay() }}>提前学习</button></div>{!todayStarted && !resting && <button className="primary-button full-button" onClick={() => setTodayStarted(true)}>开始今日学习 <span>→</span></button>}{todayStarted && !todayCompleted && <button className="primary-button full-button" onClick={() => setTodayCompleted(true)}>完成今日计划，填写学习记录 <span>→</span></button>}{todayCompleted && !recordSaved && <div className="record-after-task"><div className="panel-number">完成今日计划 / 保存学习记录</div><textarea className="record-input" placeholder="记录今天学会了什么、还不清楚什么，以及练习结果" /><button className="primary-button full-button" onClick={() => { setRecordSaved(true); setCompletedDays(days => days.includes(day) ? days : [...days, day]) }}>保存今日学习记录 <span>→</span></button></div>}{recordSaved && !resting && <div className="next-day"><div className="saved-note">已保存本次学习记录。</div><strong>是否进入下一天？</strong><div><button onClick={advanceDay}>是，继续学习</button><button onClick={() => setResting(true)}>否，先休息</button></div></div>}{resting && <div className="saved-note">学习完成，可以休息啦。想提前开始下一天吗？</div>}</article></section>}
    <footer>依据 Project Brief · 本地模拟版本 · 数据不会保存</footer>
  </main>
}
export default App
