import { useState } from 'react'

type FlowStep = 1 | 2 | 3 | 4
type Tab = 'setup' | 'research' | 'plan' | 'today'

const stages = [
  ['01', '建立起点', '目标、能力盘点与安全待确认问题'], ['02–03', '理解 Agent', '核心概念与最小练习'], ['04', '分析边界', '目标、指标、基准与可回答问题'],
  ['05–07', '验证关键能力', '取数、工具调用、问题拆解和回答'], ['08–09', '真实场景验证', '获批后核对历史 campaign'], ['10', '形成交付计划', '输出搭建计划、风险和验收方式'],
]
const resources = [['Agent 基础概念', '官方资料 · 示例', '理解 Agent'], ['工具调用与错误处理', '官方资料 · 示例', '工具调用'], ['Campaign 指标与基准', '手动资料 · 示例', '分析边界']]

function App() {
  const [step, setStep] = useState<FlowStep>(1); const [tab, setTab] = useState<Tab>('setup'); const [goal, setGoal] = useState(''); const [submitted, setSubmitted] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false)
  const go = (next: FlowStep, nextTab: Tab) => { setStep(next); setTab(nextTab) }
  const tabs: [Tab, string][] = [['setup', '建立起点'], ['research', '资料收集'], ['plan', '学习计划'], ['today', '今日启动']]
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">A</span><span>Agent Study Lab</span></div><span className="step-tag">个人学习工作台 · 模拟版本</span></header>
    <section className="hero compact"><div className="eyebrow">START YOUR LEARNING PLAN</div><h1>先建立起点，<br /><em>再开始学习。</em></h1><p>把你的目标、基础和可投入时间告诉我。我会先收集合适的资料，再制作一份由你确认的学习计划。</p></section>
    {step < 4 && <><div className="start-intro"><span className="start-kicker">LET'S START</span><strong>一起建立你的学习起点</strong><small>下面三个步骤共同完成一个目标：让今天的学习有清晰方向。</small></div><div className="flow-steps" aria-label="Let's start 建立学习起点流程">{[['1', '输入条件'], ['2', '收集资料'], ['3', '确认计划']].map(([number, label], index) => { const current = index + 1; return <button key={number} type="button" className={step === current ? 'flow-step current' : step > current ? 'flow-step done' : 'flow-step'} onClick={() => current <= step && go(current as FlowStep, tabs[index][0])}><span>{step > current ? '✓' : number}</span>{label}</button> })}</div></>}
    {step >= 4 && <section className={archiveOpen ? 'archive open' : 'archive'}><button type="button" className="archive-toggle" onClick={() => setArchiveOpen(value => !value)}><span><strong>Let's start</strong><small>学习起点已建立 · 点击查看前三步</small></span><span className="archive-chevron">⌄</span></button>{archiveOpen && <div className="archive-body"><div className="archive-steps"><button onClick={() => go(1, 'setup')}><span>✓</span>输入条件</button><button onClick={() => go(2, 'research')}><span>✓</span>收集资料</button><button onClick={() => go(3, 'plan')}><span>✓</span>确认计划</button></div><p>这三个步骤共同完成学习起点，不需要每天重新进行。你可以随时展开查看或回顾。</p></div>}</section>}
    {step < 4 && <nav className="tabs" aria-label="工作台页面">{tabs.slice(0, 3).map(([key, label]) => <button key={key} type="button" className={tab === key ? 'active' : ''} onClick={() => { if (key === 'setup' || (key === 'research' && submitted) || (key === 'plan' && step >= 3)) setTab(key) }}>{label}</button>)}</nav>}
    {tab === 'setup' && <section className="panel setup-panel"><div className="panel-number">STEP 01 / 输入学习条件</div><h2>先告诉我，你想从哪里开始</h2><p>这些信息会帮助我筛选资料，并把学习计划安排在你的真实时间里。</p><div className="form-grid"><label className="full">你的学习目标<textarea value={goal} onChange={event => setGoal(event.target.value)} placeholder="例如：我想理解 Analytics Agent 的工作方式，并做出一个安全可控的最小原型。" /></label><label>现有基础<select defaultValue="有一些相关经验"><option>刚开始了解</option><option>有一些相关经验</option><option>已经做过项目</option></select></label><label>每周可投入时间<select defaultValue="每周约 270 分钟"><option>每周约 120 分钟</option><option>每周约 270 分钟</option><option>每周约 420 分钟</option></select></label><label>资料偏好<select defaultValue="中文为主，保留英文原文"><option>中文为主，保留英文原文</option><option>英文原文优先</option><option>短文与视频优先</option></select></label><label>希望优先解决的问题<input placeholder="例如：工具调用、指标口径、安全边界" /></label></div><div className="form-actions"><span>提交后先进入资料收集，不会直接生成计划。</span><button className="primary-button" disabled={!goal.trim()} onClick={() => { setSubmitted(true); go(2, 'research') }}>保存条件，开始收集资料 <span>→</span></button></div></section>}
    {tab === 'research' && <section className="panel list-panel"><div className="panel-number">STEP 02 / 资料收集</div><h2>围绕你的目标，找到值得学习的资料</h2><p>这是一次模拟收集结果。你可以先查看主题和来源，再进入计划制作。</p><div className="research-banner"><span className="spinner">✦</span><div><strong>已根据你的学习条件整理 3 个主题</strong><small>Agent 基础 · 工具调用 · 分析边界</small></div><span className="status">收集完成</span></div><div className="stage-list">{resources.map(resource => <div className="stage-row" key={resource[0]}><span className="resource-icon">↗</span><div><strong>{resource[0]}</strong><small>{resource[1]} · {resource[2]}</small></div><span className="status">待查看</span></div>)}</div><div className="form-actions"><span>资料确认后才会进入计划。</span><button className="primary-button" onClick={() => go(3, 'plan')}>用这些资料制作计划 <span>→</span></button></div></section>}
    {tab === 'plan' && <section className="panel plan-panel"><div className="panel-number">STEP 03 / 确认学习计划</div><h2>这是为你制作的 10 周学习计划</h2><p>计划会先作为草稿展示。确认后，才会进入日常学习。</p><div className="plan-summary"><div><small>学习目标</small><strong>{goal || '理解 Analytics Agent 并完成一个最小实践'}</strong></div><div><small>时间预算</small><strong>每周 4.5 小时</strong></div><div><small>计划状态</small><strong className="accent">等待你确认</strong></div></div><div className="stage-list">{stages.slice(0, 3).map(stage => <div className="stage-row" key={stage[0]}><span className="week">{stage[0]}</span><div><strong>{stage[1]}</strong><small>{stage[2]} · 预计 2–3 小时</small></div><span className="status">草稿</span></div>)}</div><div className="form-actions"><button className="text-button" onClick={() => go(2, 'research')}>← 返回查看资料</button><button className="primary-button" onClick={() => go(4, 'today')}>确认计划，开始今日学习 <span>→</span></button></div></section>}
    {tab === 'today' && <section className="grid"><article className="panel primary"><div className="panel-number">TODAY / 今日启动</div><h2>从 3 分钟开始</h2><p>计划已经确认。今天直接进入学习任务，不需要重新走 Let's start。</p><div className="today-task"><span>01</span><div><strong>写下你对 Agent 的当前理解</strong><small>预计 15 分钟 · 完成条件：留下 3 个已知点和 3 个疑问</small></div></div><button className="primary-button full-button">开始今日任务 <span>→</span></button></article><article className="panel"><div className="panel-number">当前阶段 / WEEK 01</div><h2>Agent 基础</h2><p>从核心概念开始，逐步建立可实践的理解。</p><div className="progress"><span /></div><div className="meta"><span>本周预算</span><strong>4.5 小时</strong></div></article></section>}
    <footer>依据 Project Brief · 本地模拟版本 · 数据不会保存</footer>
  </main>
}
export default App
